import faker from 'faker';

export default [{
  title: faker.lorem.words(),
  body: faker.lorem.sentence(),
  access: 'private',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'Fake title document',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 2',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 3',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 4',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 5',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 6',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 7',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 8',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 9',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 10',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 11',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 12',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 13',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 14',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 15',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 16',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 17',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}, {
  title: 'test document 18',
  body: faker.lorem.paragraph(),
  access: 'public',
  ownerRoleId: 2,
  userId: 1,
}];
