export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CREATE_DOCUMENT_BY_USER_SUCCESS =
  'CREATE_DOCUMENT_BY_USER_SUCCESS';
export const LOAD_WELCOME_PAGE_DOCUMENT_SUCCESS =
  'LOAD_WELCOME_PAGE_DOCUMENT_SUCCESS';
export const LOAD_AUTHORIZE_TO_VIEW_DOCUMENT_SUCCESS =
  'LOAD_AUTHORIZE_TO_VIEW_DOCUMENT_SUCCESS';
export const LOAD_USER_DOCUMENT_SUCCESS = 'LOAD_USER_DOCUMENT_SUCCESS';
export const DELETE_USER_DOCUMENT_SUCCESS = 'DELETE_USER_DOCUMENT_SUCCESS';

export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const DELETE_USER_PROFILE_SUCCESS = 'DELETE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_DOCUMENT_SUCCESS = 'UPDATE_USER_DOCUMENT_SUCCESS';

export const CREATE_USER_ROLE_SUCCESS = 'CREATE_USER_ROLE_SUCCESS';
export const LOAD_USER_ROLE_SUCCESS = 'LOAD_USER_ROLE_SUCCESS';
export const DELETE_USER_ROLE_SUCCESS = 'DELETE_USER_ROLE_SUCCESS';
export const DELETE_DOCUMENT_BY_ADMIN_SUCCESS =
  'DELETE_DOCUMENT_BY_ADMIN_SUCCESS';
export const UPDATE_USER_DOCUMENT_BY_ADMIN_SUCCESS =
  'UPDATE_USER_DOCUMENT_BY_ADMIN_SUCCESS';

export const UPDATE_USER_PROFILE_BY_ADMIN_SUCCESS =
  'UPDATE_USER_PROFILE_BY_ADMIN_SUCCESS';
export const UPDATE_SINGLE_USER_BY_ADMIN_SUCCESS =
  'UPDATE_SINGLE_USER_BY_ADMIN_SUCCESS';

export const LOAD_ALL_USERS_SUCCESS = 'LOAD_ALL_USERS_SUCCESS';
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS';

export const LOAD_ALL_DOCUMENTS_SUCCESS = 'LOAD_ALL_DOCUMENTS_SUCCESS';

export const SEARCH_USER_BY_USERNAME_SUCCESS =
  'SEARCH_USER_BY_USERNAME_SUCCESS';
export const SEARCH_DOCUMENTS_BY_TITLE_SUCCESS =
  'SEARCH_DOCUMENTS_BY_TITLE_SUCCESS';
export const SEARCH_DOCUMENTS_BY_TITLE_ON_DASHBOARD_SUCCESS =
  'SEARCH_DOCUMENTS_BY_TITLE_ON_DASHBOARD_SUCCESS';
