export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const DELETE_USER_PROFILE_SUCCESS = 'DELETE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_DOCUMENT_SUCCESS = 'UPDATE_USER_DOCUMENT_SUCCESS';

export const LOAD_USER_ROLE_SUCCESS = 'LOAD_USER_ROLE_SUCCESS';

export const LOAD_ALL_USERS_SUCCESS = 'LOAD_ALL_USERS_SUCCESS';
